/* ---------- настройки сезона ---------- */
var PTS_PER_HOUR = 10, SPRINT_BONUS = 30, START_TOKENS = 3, ACH_BONUS = 50, DOTA_DAY = 5, DOTA_WEEK = 75;
var CATS = {horror:'Хоррор', action:'Экшен', rpg:'RPG', story:'Сюжетная', indie:'Инди', hard:'Хардкор'};
var UNIVERSAL = [
{id:'u_noguide', t:'Без гайдов и подсказок из интернета', p:30},
{id:'u_hard', t:'Сложность выше стандартной', p:40}
];
var RANKS = [
{id:'recruit', n:'Рекрут', p:0},
{id:'guard', n:'Страж', p:200, chest:{token:1}},
{id:'knight', n:'Рыцарь', p:500, chest:{clock:1, token:1}},
{id:'hero', n:'Герой', p:900, chest:{boost:1, token:1}},
{id:'legend', n:'Легенда', p:1400, chest:{clock:1, boost:1}},
{id:'ancient', n:'Властелин', p:2000, chest:{token:2, boost:1}},
{id:'divine', n:'Божество', p:2800, chest:{clock:2, boost:1}},
{id:'titan', n:'Титан', p:3800, chest:{token:2, clock:2, boost:2}}
];
var CLOCK_DAYS = 7, BOOST_MULT = 1.5;
var CHEST_SVG = '<svg class="chest-ico" viewBox="0 0 24 24" width="30" height="30" aria-hidden="true"><path d="M3 10h18v9a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z" fill="currentColor" opacity=".8"/><path d="M4 5h16a1 1 0 0 1 1 1v3H3V6a1 1 0 0 1 1-1z" fill="currentColor"/><rect x="10" y="8" width="4" height="5" rx="1" fill="var(--accent-soft)"/></svg>';
var EXAMPLE_REWARDS = [
{id:'r1', pts:150, text:'Заказать пиццу или шаурму'},
{id:'r2', pts:400, text:'Игра из списка желаемого до 400 грн'},
{id:'r3', pts:750, text:'Сет или скин в Доте до 300 грн'},
{id:'r4', pts:1200, text:'Любая игра до 1000 грн'},
{id:'r5', pts:1800, text:'Геймпад или гарнитура'},
{id:'r6', pts:2600, text:'Большая награда на твой выбор'},
{id:'r7', pts:3800, text:'Планшет для кино в кровати'}
];
/* Игры из библиотеки Steam. h — основной сюжет по HowLongToBeat (примерно), r — порядок маршрута, s — уже наиграно в Steam. */
var GAMES = [
{id:'re4', n:'Resident Evil 4', h:16, c:['horror','action'], r:1, note:'Скачан', ch:[{id:'hc', t:'Пройди на Hardcore или Professional', p:60}, {id:'req', t:'Выполни 10 просьб торговца (синие записки)', p:40}]},
{id:'shf', n:'Silent Hill f', h:12, c:['horror'], r:2, note:'Качается', ch:[{id:'ng', t:'Пройди повторно (NG+) и открой другую концовку', p:80}]},
{id:'gow', n:'God of War', h:21, c:['action'], r:3, ch:[{id:'valk', t:'Победи хотя бы одну валькирию', p:60}]},
{id:'stray', n:'Stray', h:5, c:['indie'], r:4, ch:[{id:'b12', t:'Собери все воспоминания B-12', p:40}]},
{id:'gotg', n:"Marvel's Guardians of the Galaxy", h:17, c:['action'], r:5},
{id:'e33', n:'Clair Obscur: Expedition 33', h:30, c:['rpg'], r:6, ch:[{id:'opt', t:'Победи необязательного босса', p:50}]},
{id:'dbh', n:'Detroit: Become Human', h:12, c:['story'], r:7, ch:[{id:'alive', t:'Доведи до финала всех трёх героев живыми', p:60}]},
{id:'got', n:'Ghost of Tsushima', h:25, c:['action'], r:8, ch:[{id:'myth', t:'Пройди все мифические сказания Цусимы', p:50}]},
{id:'hb', n:"Hellblade: Senua's Sacrifice", h:7, c:['story','horror'], r:9, ch:[{id:'lore', t:'Найди все лор-камни', p:30}]},
{id:'rdr2', n:'Red Dead Redemption 2', h:50, c:['action'], r:10, ch:[{id:'epi', t:'Пройди эпилог до финальных титров', p:50}]},
{id:'w3', n:'The Witcher 3: Wild Hunt', h:52, c:['rpg'], r:11, wr:1, rel:'2026-09-29T10:00:00Z', ch:[{id:'dm', t:'Пройди на сложности «На смерть!»', p:80}, {id:'gwent', t:'Выиграй турнир по гвинту в Новиграде', p:50}, {id:'velen', t:'Выполни все ведьмачьи заказы в Велене', p:50}]},
{id:'w3hos', n:'The Witcher 3: Hearts of Stone', h:10, c:['rpg'], wr:2, note:'После основной игры', ch:[{id:'nodeath', t:'Ни одной смерти на боссах дополнения', p:60}]},
{id:'w3baw', n:'The Witcher 3: Blood and Wine', h:25, c:['rpg'], wr:3, note:'Финал ведьмачьей арки', ch:[{id:'corvo', t:'Полностью обустрой винодельню Корво Бьянко', p:60}, {id:'gm', t:'Собери гроссмейстерский комплект ведьмачьего снаряжения', p:50}]},
{id:'bg3', n:"Baldur's Gate 3", h:75, c:['rpg'], coop:true, r:12, ch:[{id:'friend', t:'Пройди вместе с другом', p:60}]},
{id:'cp77', n:'Cyberpunk 2077', h:25, c:['rpg'], s:28.7},
{id:'dl2', n:'Dying Light 2', h:22, c:['action','horror'], coop:true, s:25},
{id:'stk2', n:'S.T.A.L.K.E.R. 2: Heart of Chornobyl', h:40, c:['action'], s:5.2},
{id:'dd2', n:"Dragon's Dogma 2", h:30, c:['rpg'], s:5},
{id:'indika', n:'INDIKA', h:5, c:['story','indie'], s:3.7},
{id:'re2', n:'Resident Evil 2', h:9, c:['horror'], s:3.6, ch:[{id:'both', t:'Пройди за Леона и за Клэр', p:60}]},
{id:'re8', n:'Resident Evil Village', h:10, c:['horror']},
{id:'re7', n:'Resident Evil 7 Biohazard', h:9, c:['horror']},
{id:'re9', n:'Resident Evil Requiem', h:12, c:['horror']},
{id:'re3', n:'Resident Evil 3', h:6, c:['horror','action']},
{id:'sh2', n:'Silent Hill 2', h:16, c:['horror']},
{id:'dsp', n:'Dead Space', h:12, c:['horror']},
{id:'tew', n:'The Evil Within', h:15, c:['horror']},
{id:'tew2', n:'The Evil Within 2', h:15, c:['horror']},
{id:'ol1', n:'Outlast', h:5, c:['horror']},
{id:'ol2', n:'Outlast 2', h:7, c:['horror']},
{id:'ln1', n:'Little Nightmares', h:4, c:['horror','indie']},
{id:'ln2', n:'Little Nightmares II', h:6, c:['horror','indie']},
{id:'apt', n:'A Plague Tale: Innocence', h:11, c:['story']},
{id:'callisto', n:'The Callisto Protocol', h:11, c:['horror']},
{id:'aw', n:'Alan Wake', h:12, c:['horror','action']},
{id:'quarry', n:'The Quarry', h:10, c:['horror','story']},
{id:'scorn', n:'Scorn', h:5, c:['horror','indie']},
{id:'gowr', n:'God of War Ragnarök', h:26, c:['action']},
{id:'hzd', n:'Horizon Zero Dawn', h:22, c:['action']},
{id:'unch', n:'UNCHARTED: Legacy of Thieves', h:22, c:['action']},
{id:'ak1', n:'Batman: Arkham Asylum', h:12, c:['action']},
{id:'ak2', n:'Batman: Arkham City', h:13, c:['action']},
{id:'ak3', n:'Batman: Arkham Knight', h:17, c:['action']},
{id:'control', n:'Control', h:12, c:['action']},
{id:'dstr', n:'Death Stranding', h:40, c:['action','story']},
{id:'daysgone', n:'Days Gone', h:36, c:['action']},
{id:'tr13', n:'Tomb Raider (2013)', h:11, c:['action']},
{id:'rottr', n:'Rise of the Tomb Raider', h:15, c:['action']},
{id:'sottr', n:'Shadow of the Tomb Raider', h:15, c:['action']},
{id:'mafia1', n:'Mafia: Definitive Edition', h:12, c:['action']},
{id:'mafia2', n:'Mafia II: Definitive Edition', h:11, c:['action']},
{id:'mafia3', n:'Mafia III: Definitive Edition', h:22, c:['action']},
{id:'metro1', n:'Metro 2033 Redux', h:8, c:['action','horror']},
{id:'metro2', n:'Metro: Last Light Redux', h:9, c:['action']},
{id:'metro3', n:'Metro Exodus', h:16, c:['action']},
{id:'bsi', n:'BioShock Infinite', h:12, c:['action']},
{id:'bs2', n:'BioShock 2', h:10, c:['action']},
{id:'hl2', n:'Half-Life 2', h:13, c:['action']},
{id:'sdogs', n:'Sleeping Dogs', h:16, c:['action']},
{id:'kena', n:'Kena: Bridge of Spirits', h:11, c:['action','indie']},
{id:'ladg', n:'Like a Dragon Gaiden', h:11, c:['action']},
{id:'disco', n:'Disco Elysium', h:22, c:['rpg','story']},
{id:'kcd1', n:'Kingdom Come: Deliverance', h:43, c:['rpg']},
{id:'kcd2', n:'Kingdom Come: Deliverance II', h:50, c:['rpg']},
{id:'nier', n:'NieR:Automata', h:20, c:['rpg','action']},
{id:'p5r', n:'Persona 5 Royal', h:100, c:['rpg']},
{id:'ylad', n:'Yakuza: Like a Dragon', h:44, c:['rpg']},
{id:'ff16', n:'Final Fantasy XVI', h:35, c:['rpg','action']},
{id:'dos2', n:'Divinity: Original Sin 2', h:60, c:['rpg'], coop:true},
{id:'hogw', n:'Hogwarts Legacy', h:26, c:['rpg']},
{id:'arise', n:'Tales of Arise', h:40, c:['rpg']},
{id:'brante', n:'The Life and Suffering of Sir Brante', h:9, c:['story','indie']},
{id:'untilthen', n:'Until Then', h:10, c:['story','indie']},
{id:'unbound', n:'A Space for the Unbound', h:11, c:['story','indie']},
{id:'lis2', n:'Life is Strange 2', h:15, c:['story']},
{id:'tmw', n:'Tell Me Why', h:9, c:['story']},
{id:'spirit', n:'Spiritfarer', h:27, c:['indie']},
{id:'papers', n:'Papers, Please', h:5, c:['indie']},
{id:'dutm', n:'Deliver Us The Moon', h:6, c:['story','indie']},
{id:'invinc', n:'The Invincible', h:8, c:['story']},
{id:'alters', n:'The Alters', h:20, c:['story']},
{id:'portal1', n:'Portal', h:3, c:['indie']},
{id:'split', n:'Split Fiction', h:14, c:['action'], coop:true},
{id:'portal2', n:'Portal 2', h:8, c:['indie'], coop:true},
{id:'wwhf', n:'We Were Here Forever', h:7, c:['indie'], coop:true},
{id:'bl2', n:'Borderlands 2', h:30, c:['action'], coop:true},
{id:'bl3', n:'Borderlands 3', h:23, c:['action'], coop:true},
{id:'sekiro', n:'Sekiro: Shadows Die Twice', h:30, c:['action','hard']},
{id:'er', n:'ELDEN RING', h:55, c:['rpg','hard']},
{id:'liesofp', n:'Lies of P', h:30, c:['action','hard']},
{id:'ds3', n:'DARK SOULS III', h:32, c:['action','hard']},
{id:'ninesols', n:'Nine Sols', h:21, c:['action','hard','indie']},
{id:'sifu', n:'Sifu', h:7, c:['action','hard']}
];
